### ISSUE TITLE
Index Already Exists

### ISSUE THREAD

**Issue by gopiprasanthpotipireddy** [Hygieia/hygieia-deploy-xldeploy-collector#3]
Hi ,
While running the xldeploy collector getting index already exists with different options error for metadata indexes.

**Comment by rvema** [comment]
Let me check and get it fixed

**Comment by rvema** [comment]
@Courtneyp123 will fix this issue

**Comment by Courtneyp123** [comment]
@gopiprasanthpotipireddy PR #4 should fix the issue.  Please retest and let me know if it is fixed.  Thanks!

**Comment by gopiprasanthpotipireddy** [comment]
@Courtneyp123 @rvema Tested the issue and working fine now .Thanks for the support.

**Comment by rvema** [comment]
Thanks @gopiprasanthpotipireddy for confirming, we will close this issue as it is resolved.
